language: python

env:
 - PYTHON=python

python:
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gsl-bin libgsl0-dbg libgsl0-dev libgsl0ldbl libboost-all-dev swig

script:
 - make PYTHON=$PYTHON src tests
 - make PYTHON=$PYTHON python

